### ISSUE TITLE
error compiling on osx. __INT64_MAX__ not defined

### ISSUE THREAD

**Issue by wardrums** [Squashwell/bepuik#1]
Hey mate, really keen to test this out, and provide a test build for osx.

im compiling on OSX 10.8.5, xcode 4.6.3 (not the latest version) and have all the comandline tools install.
Ive been successfully compiling blender for a few months.

ive disabled most of the blender options for modifiers, cycles etc.

the error message im getting is 
/blender-bepuik/bepuik/intern/bepuik/intern/PermutationMapper.cpp:83:48: error: use of undeclared identifier '**INT64_MAX**'
        permutationIndex = value < 0 ? value + **INT64_MAX** + 1 : value;

/blender-bepuik/bepuik/intern/bepuik/intern/PermutationMapper.cpp:89:45: error: use of undeclared identifier '**INT64_MAX**'
            currentOffset = currentOffset + **INT64_MAX** + 1;

"

I was able to get it compiling by changing them to  "UINTMAX_MAX" and also adding:
# include <inttypes.h>

i didnt want to fork and patch as this might not be relivant for windows or linux machines.

i have it compiling fine now, but i havent tested the new Bepuik stuff. once i have i can upload a build for you to distribute if you want.

**Comment by Squashwell** [comment]
Thanks for the report, I'll check it out.

... now fixed.

**Comment by Squashwell** [comment]
And a mac release would be great, thanks.

**Comment by wardrums** [comment]
http://www.graphicall.org/1118/

**Comment by Squashwell** [comment]
Thanks! I'll link the graphicall link in the releases so you only need to update one place :)
