### ISSUE TITLE
Failed to compile due to Werror=return-type

### ISSUE THREAD

**Issue by ddvogt** [Squashwell/bepuik#2]
Dear Squashwell, 
I noticed that the latest commit on branch bepuik does not compile due to an uncontrolled end in a non-void function. 

Adding "return false" to intern/bepuik/intern/Quaternion.cpp:346 instead of "false" fixes the issue. 

Kind regards

**Comment by Squashwell** [comment]
A delayed thanks!

Looks like this error existed from the beginning and my compile settings ignored it.
